In [89]:
import pandas as pd
import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("Training.csv")

In [8]:
df.head()
#Found it has classificiation problem

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
df.shape

(4920, 133)

In [6]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [7]:
len(df['prognosis'].unique())

41

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [13]:
X=df.drop('prognosis',axis=1)

In [14]:
y= df['prognosis']

In [22]:
X.shape

(4920, 132)

In [21]:
y.shape

(4920,)

### Will Use Label Encoder To get the String value into  integer one

In [24]:
le=LabelEncoder()
le.fit(y)
Y=le.transform(y)

In [25]:
Y

array([15, 15, 15, ..., 38, 35, 27])

## train Split the model

In [48]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=20)

In [49]:
x_train.shape

(3690, 132)

In [50]:
y_train.shape

(3690,)

## Let's train top 5 classificiation models

In [55]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np

#Create A dictionary to stoire models
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

models = {
    "SVC": SVC(kernel='linear'),  # corrected 'liner' to 'linear'
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    "kNeighbours": KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB": MultinomialNB()
}

# Ensure you have defined x_train, y_train, x_test, y_test before the loop

for model_name, model in models.items():
    # Train the model
    model.fit(x_train, y_train)
    
    # Test the model
    predictions = model.predict(x_test)
    # Test the model
    accuracy = accuracy_score(y_test,predictions)
    # Test the model
    cm = confusion_matrix(y_test,predictions)
    
    # Print or store the predictions
    print(f"Model: {model_name}")
    print(f"Model: {model_name} accaccuracy : {accuracy}")
    print(f"Confusion Matrix:{model_name}")
    print(np.array2string(cm,separator=','))
    print(f"Predictions: {predictions}")



Model: SVC
Model: SVC accaccuracy : 1.0
Confusion Matrix:SVC
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,22,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,27, 0, 0],
 [ 0, 0, 0,..., 0,38, 0],
 [ 0, 0, 0,..., 0, 0,28]]
Predictions: [40  6 16 ... 39  1 34]
Model: RandomForest
Model: RandomForest accaccuracy : 1.0
Confusion Matrix:RandomForest
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,22,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,27, 0, 0],
 [ 0, 0, 0,..., 0,38, 0],
 [ 0, 0, 0,..., 0, 0,28]]
Predictions: [40  6 16 ... 39  1 34]
Model: GradientBoosting
Model: GradientBoosting accaccuracy : 1.0
Confusion Matrix:GradientBoosting
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,22,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,27, 0, 0],
 [ 0, 0, 0,..., 0,38, 0],
 [ 0, 0, 0,..., 0, 0,28]]
Predictions: [40  6 16 ... 39  1 34]
Model: kNeighbours
Model: kNeighbours accaccuracy : 1.0
Confusion Matrix:kNeighbours
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,22,..., 0

## Lets's use the single model to check the predictions

In [64]:
# kNeighbours=KNeighborsClassifier(n_neighbors=5)
# kNeighbours.fit(x_train,y_train)
# ypred=kNeighbours.predict(x_test)
# accuracy_score=(y_test,ypred)
# print(accuracy_score)

In [67]:
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)
ypred=svc.predict(x_test)
accuracy_score=(y_test,ypred)
print(accuracy_score)

(array([40,  6, 16, ..., 39,  1, 34]), array([40,  6, 16, ..., 39,  1, 34]))


In [76]:
#lets's save the model which have nbest accuracy for us
import pickle
pickle.dump(svc,open("svc.pkl",'wb'))

In [78]:
# #load model
# svc-=pickle.load(open("svc.pkl",'rb'))

with open("svc.pkl", 'rb') as file:
    svc = pickle.load(file)

In [79]:
x_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4037        0          0                     0                    0   
4191        0          0                     0                    0   
432         0          0                     0                    0   
1266        1          0                     0                    0   
3765        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2871        0          0                     0                    1   
4484        0          0                     0                    0   
1946        0          0                     0                    0   
2917        0          0                     0                    0   
686         0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4037          0       0           1             0        0                 0   
4191          0       0           0             0        0                 0   
432           0       0           0             1        1                 0   
1266          0       0           0             0        0                 0   
3765          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2871          1       1           0             0        0                 0   
4484          0       1           0             0        0                 0   
1946          0       0           0             0        0                 0   
2917          0       0           0             0        0                 0   
686           0       1           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4037  ...                   0           0         0             0   
4191  ...                   0           0         0             0   
432   ...                   0           0         0             0   
1266  ...                   0           0         0             0   
3765  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2871  ...                   0           0         0             0   
4484  ...                   0           0         0             0   
1946  ...                   0           0         0             0   
2917  ...                   0           0         0             0   
686   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4037                    0                     0                   0        0   
4191                    0                     0                   0        0   
432                     0                     0                   0        0   
1266                    0                     0                   0        0   
3765                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2871                    0                     0                   0        0   
4484                    0                     0                   0        0   
1946                    0                     0                   0        0   
2917                    0                     0                   0        0   
686                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4037                     0                  0  
4191                     0                  0  
432                      0                  0  
1266                     0                  0  
3765                     0                  0  
...                    ...                ...  
2871                     0                  0  
4484              

In [80]:
x_test.iloc[0].values

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [90]:
#Our modelk train on 2d data so we need to reshape it 
svc.predict(x_test.iloc[0].values.reshape(1,-1))

array([40])

In [91]:
print("Model Predicyed Label",svc.predict(x_test.iloc[0].values.reshape(1,-1)))
print("Actaul Label",y_test[0] )

Model Predicyed Label [40]
Actaul Label 40


In [92]:
print("Model Predicyed Label",svc.predict(x_test.iloc[10].values.reshape(1,-1)))
print("Actaul Label",y_test[10] )

Model Predicyed Label [20]
Actaul Label 20


In [86]:
y_test[0]

40

## Load more data set for recommendation System for medicine

In [99]:
sym_de=pd.read_csv("symtoms_df.csv")
precaution=pd.read_csv('precautions_df.csv')
workout=pd.read_csv('workout_df.csv')
desc=pd.read_csv('description.csv')
medications=pd.read_csv('medications.csv')
diets=pd.read_csv('diets.csv')

In [119]:
#==========================helper funtions================
def helper(dis):
    description = desc[desc['Disease'] == predicted_disease]['Description']
    description = " ".join([w for w in desc])

    pre = precaution[precaution['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']


    return description,pre,med,die,wrkout


symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

# Model Prediction function
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]

In [121]:
#test 1 :
symptoms=input("Enter Your Symptoms........")
user_symp=[s.strip() for s in symptoms.split(',')]
user_symptoms=[symp.strip("[]' ") for symp in user_symp]
predicted_disease=get_predicted_value(user_symptoms)

description, pre, med, die, wrkout = helper(predicted_disease)

print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(description)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter Your Symptoms........ itching','skin_rash'


=================predicted disease============
Fungal infection
=================description==================
Disease Description
=================precautions==================
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
=================medications==================
5 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
=================workout==================
6 :  Avoid sugary foods
7 :  Consume probiotics
8 :  Increase intake of garlic
9 :  Include yogurt in diet
10 :  Limit processed foods
11 :  Stay hydrated
12 :  Consume green tea
13 :  Eat foods rich in zinc
14 :  Include turmeric in diet
15 :  Eat fruits and vegetables
=================diets==================
16 :  ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']


In [108]:
predicted_disease

'Fungal infection'

In [114]:
#use filters to get the data from f8ile
descr=desc[desc['Disease']==predicted_disease]['Description']
descr=" ".join([w for w in descr])
descr

'Fungal infection is a common skin condition caused by fungi.'

In [122]:
import sklearn
print(sklearn.__version__)

1.4.0
